### ISSUE TITLE
NameError: (eval):15: uninitialized constant EvernoteVim

### ISSUE THREAD

**Issue by dechimp** [trobrock/evernote.vim#7]
Getting this error when running Vim (version 7.3.754):

```
Error detected while processing /Users/dechimp/.janus/vim-evernote/plugin/evernote.vim:
line   46:
NameError: (eval):15: uninitialized constant EvernoteVim
```

If you don't know what janus is, it's a plugin collection for Vim and `.janus/` is basically like the `.vim/bundle/` folder for installing plugins

**Comment by trobrock** [comment]
I would love to get this working again and support vundle, but I do not have time right now. Feel free to send a PR and I'll review it quickly
